### ISSUE TITLE
Loosen peer dependency requirements

### ISSUE THREAD

**Issue by adeem** [snowplow-incubator/snowplow-react-native-tracker#105]
**Describe the bug**
We currently have 0.1.1 in our project. Now we want to upgrade it and get an error as stated below. 

```
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Raisin@0.0.1
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.59.8" from @snowplow/react-native-tracker@0.1.3
npm ERR! node_modules/@snowplow/react-native-tracker
npm ERR!   @snowplow/react-native-tracker@"^0.1.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**To Reproduce**
When we run following, it says that tracker has older version of react-native. 
```
npm info @snowplow/react-native-tracker peerDependencies
{ 'react-native': '^0.59.8', react: '^16.8.6' }

```
**Expected behavior**
Upgrading should work fine

**Smartphone (please complete the following information):**
React native version I got is following

`"react-native": "0.63.4",`

**Comment by colmsnowplow** [comment]
Thanks for raising! 

At first glance seems like we enforce versions where we shouldn't (using `^` where we should use `>=`) - bear with us while we double-check that no conflict exists, will release the fix as soon as we've done so.

**Comment by colmsnowplow** [comment]
Sorry for the hassle @adeem - Should be good to go with the latest version (0.1.5) - please don't hesitate to raise another issue if there's any problems. :)
