### ISSUE TITLE
Support custom `platform` field

### ISSUE THREAD

**Issue by fasci** [snowplow-incubator/snowplow-react-native-tracker#109]
**Is your feature request related to a problem? Please describe.**
The React Native tracker lets me choose to optionally send a `platformContext`, but does not allow me to set a custom `platform` field as can be done with the JS tracker, for example.
As we are developing a TV app, we want to be able to set the `platform` to `tv`. It is currently set automatically to `mob` on Android TV, and `pc` on tvOS (simulator).
This conflicts with our actual mobile apps, so it would be great to be able to customize this.

**Describe the solution you'd like**
When initializing the tracker, I would like to be able to set:
`platform: 'tv'` similar to how it is done for the JS tracker.

**Describe alternatives you've considered**
An alternative would be to somehow customize/overwrite the `platformContext`.

**Comment by colmsnowplow** [comment]
At first glance that seems like a fair ask alright.

I'm not sure overwriting the platform context is a good solution as that maps to a standard method. However a very reasonable approach in the short term is to use a custom context to do the same thing. 

[Here's a quick overview if you're not familiar](https://docs.snowplowanalytics.com/docs/understanding-tracking-design/predefined-vs-custom-entities/), once you have a schema you'd use the `ctxt` argument (which takes an array of self-describing data - eg `[{"schema": "iglu:com.vendor/name/jsonschema/1-0-0, "data": {"platform": "tv"}]`

**Comment by fasci** [comment]
Thanks for the fast answer, @colmsnowplow!
We'll think about adding a custom context for the platform as a quick fix.

**Comment by adatzer** [comment]
This is resolved as part of https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/128 . (cc @fasci )
More specifically, by upgrading iOS and Android trackers to v2, it is now possible to set the `platform` field using the `devicePlatform` property of the `trackerConfig`, when initializing the tracker: [Documentation](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/react-native-tracker/introduction/#trackerconfiguration).
Closing.
