### ISSUE TITLE
Do we need to do something in Android native side during integration

### ISSUE THREAD

**Issue by hipages-ligang** [snowplow-incubator/snowplow-react-native-tracker#137]
I integrated React Native to my existing Android project.
Now, I'm going to integrate snowplow-react-native-tracker to React Native side.
According to the document: [Quick start guide](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/react-native-tracker/quick-start-guide/), I finished the steps for js side, and then I met the warning when I trying to track event: 
`
SnowplowTracker:createTracker: null is not an object (evaluating 'RNSnowplowTracker.createTracker').
`

I guess we need to something in Android Native side. Such as adding corresponding package to packageList when init ReactInstanceManager.

This is not mentioned in documents.

My question is:
How should I do for Android native side to make the tracker works.

Suggestion:
Please make the document more detailed.

**Comment by paulboocock** [comment]
Thanks for the question @hipages-ligang 

In a typical set up I don't believe anything extra should be required. It's usually on the iOS side of things you need to ensure you've installed the pods. 

I'd suggest perhaps taking a look at the demo app in this repository to see how we've instrumented the tracker there. Instructions on how to run it are in the [README](https://github.com/snowplow/snowplow-react-native-tracker/blob/master/README.md). 

Also, for future reference, Github probably isn't the best place to ask questions. You'll have more chance of finding other community members (and the Snowplows maintainers too) on our [Discourse forum](https://discourse.snowplowanalytics.com/).

**Comment by hipages-ligang** [comment]
Thank you @paulboocock for your prompt reply.
