### ISSUE TITLE
Add option to add custom headers

### ISSUE THREAD

**Issue by AlexBenny** [snowplow-incubator/snowplow-react-native-tracker#165]
**Is your feature request related to a problem? Please describe.**
Some users want to place the Snowplow collector behind an authenticated gateway which requires custom headers to be sent with the request. Currently, the tracker is unable to send requests successfully to this as there is no way to easily add custom headers to the request.

**Describe the solution you'd like**
Create a configuration option that allows for custom headers to be added.
The added custom headers would configure the native trackers wrapped by the react native tracker.

**Comment by shalinibnair** [comment]
Javascript tracker seems to have this option but is missing in the react native side.
This is a high priority issue for us
https://github.com/snowplow/snowplow-javascript-tracker/pull/1024/commits/0b0b98e6b6a33ffa7c9bc4acf1dfe8ea14eae351

**Comment by shalinibnair** [comment]
@AlexBenny  Is there an alternative that you can suggest to handle this gap, till the fix for this gets released.
We are using Krakend in between, which routs the requests to collector end point. And without auth we cannot make any progress on this.

**Comment by matus-tomlein** [comment]
Hi @shalinibnair, the only alternative that comes to mind at the moment is for you to initialize the trackers with the custom headers in your native Android and iOS code using the native mobile tracker APIs – you could make use of the [`requestHeaders` property in the `NetworkConfiguration`](https://snowplow.github.io/snowplow-objc-tracker/interface_s_p_network_configuration.html#a2bb2cb28f4a9c0cbc25905b3545da63c).

When you initialize the tracker in the native code like that, it will also be available in your React native code under the same namespace. So you could initialize the tracker in Kotlin/Swift and then just track events as you do now from React native. [Here is a bit more](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/react-native-tracker/advanced-usage/#accessing-the-tracker-from-native-code) about how to access the tracker in the native code of a React native app.

**Comment by shalinibnair** [comment]
@matus-tomlein , Thank you for the response. Could you please guide me a bit more on this.
Are you suggesting to make changes to RNSnowPlowTrackerModule.java. If so I am having difficulty in identifying how to pass the data in the NetworkConfiguration.

**Comment by matus-tomlein** [comment]
@shalinibnair Sorry for not being more clear. I didn't mean for you to make any changes in the tracker library. I meant that you can initialize your tracker instance from the native Java/Swift/... code in **your** app. So if we are talking about Android code, it might be in something like `android/app/src/main/java/com/your_vendor/MainApplication.java` (similar in the iOS part). You should be able to find a method that is called on app startup and call the `Snowplow.createTracker(...)` function on the Android/iOS tracker library to intialize the tracker with custom requests headers. [Here is a quick start](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/mobile-trackers/mobile-trackers-v3-0/quick-start-guide/) for configuring the native trackers.

In the demo app in this repository, there is an example where a tracker is initialized in React Native code and an event is tracked in the native Java/Swift code. This is not exactly what you want (you want the other way – initialize in native and track in React). But just for illustration, [here](https://github.com/snowplow/snowplow-react-native-tracker/blob/master/DemoApp/android/app/src/main/java/com/demoapp/MainActivity.java#L25) is the line where the event is tracked.

I'm not sure if this solution can work for you, but I can't think of any other workaround. We're happy to help if you have further questions, but we're going slightly off-topic of this issue, so if you need more help initializing the tracker in native code, please open a [Discourse post](https://discourse.snowplowanalytics.com/) for it.

**Comment by shalinibnair** [comment]
@matus-tomlein  Thank you for addressing this. This is very useful for us

**Comment by matus-tomlein** [comment]
Happy to hear that! Please let us know if you have any other feedback.
