### ISSUE TITLE
Android CircleCi build failed: Could not resolve com.snowplowanalytics:snowplow-android-tracker:4.0.+

### ISSUE THREAD

**Issue by matthewparavati** [snowplow-incubator/snowplow-react-native-tracker#183]
**Describe the bug**
Android build failed on circleci after running this command:
`./gradlew app:assemble app:assembleAndroidTest -DtestBuildType=release --no-daemon --max-workers=2 -PreactNativeArchitectures=x86,x86_64`

The output we see is below:
```
Could not resolve com.snowplowanalytics:snowplow-android-tracker:4.0.+.
     Required by:
         project :app > project :snowplow_react-native-tracker
      > Failed to list versions for com.snowplowanalytics:snowplow-android-tracker.
         > Unable to load Maven meta-data from https://www.jitpack.io/com/snowplowanalytics/snowplow-android-tracker/maven-metadata.xml.
            > Could not GET 'https://www.jitpack.io/com/snowplowanalytics/snowplow-android-tracker/maven-metadata.xml'. Received status code 521 from server:
```

**To Reproduce**
Create an android build on circleci 😅 Not an easy thing to reproduce as I actually haven't seen this issue when creating an android build locally

**Expected behavior**
Android builds successfully on circleci without snowplow dependency error

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android (emulator)
 - Browser: N/A
 - Version: api 31

**Additional context**
We're using version `1.3.0` of `@snowplow/react-native-tracker`. We've been using it for a while now with no issues. This circleci build issue just started last night and I've seen it twice again today. Locally, android is building fine.

Do I possibly need to reach out to circleci support instead? Or let me know if I can provide any other information.

**Comment by matthewparavati** [comment]
🤦 I was doing cache testing/updates on circleci yesterday and didn't put 2 and 2 together that it was probably caused by me reseting the cache. Looking up jitpack now, seems like this has been an ongoing issue since ~end of september for some people. I'm trying to update our local maven jitpack url in the build.gradle per this [comment](https://github.com/jitpack/jitpack.io/issues/5239#issuecomment-1260780833) but not very confident that will work/help

Should I close this issue or leave it open for now?

**Comment by matus-tomlein** [comment]
Hi @matthewparavati, glad you were able to figure out the problem! I think we can close the issue since it doesn't seem under our control, but please reopen and update when you find something else that is relevant. I'm sure this could also be relevant for other users struggling with similar issues.
