### ISSUE TITLE
screen_view and deep_link_received events fail validation on page_urlscheme

### ISSUE THREAD

**Issue by jochem725** [snowplow-incubator/snowplow-react-native-tracker#190]
**Describe the bug**
screen_view and deep_link_received events fail validation in the enricher on page_urlscheme (atomic schema) if the url scheme of a deep link is larger than [16 characters](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/atomic/jsonschema/1-0-0#L136). Deep links can have a url scheme that is longer than 16 characters (e.g. `someappwithaverylongscheme://...`).

I can work around it by truncating the url scheme before logging, but ideally I don't lose this data.

**To Reproduce**
Track an event via a deep link (e.g. a `trackDeepLinkReceivedEvent()`) with a url that has a urlscheme longer than 16 characters. 

**Expected behavior**
These events should pass validation.

**Smartphone (please complete the following information):**
 - Device: iPhone/Android devices
 - OS: iOS/Android
 - Version: snowplow-react-native-tracker 1.4.0

**Additional context**
I believe this workaround ([iOS](https://github.com/snowplow/snowplow-objc-tracker/blob/ec912a566073615ebcc9dc3a4c6b96a1cc6ed7e7/Snowplow/Internal/Tracker/SPTracker.m#L637  
)/[Android](https://github.com/snowplow/snowplow-objc-tracker/blob/ec912a566073615ebcc9dc3a4c6b96a1cc6ed7e7/Snowplow/Internal/Tracker/SPTracker.m#L637  
)) causes it.

**Comment by matus-tomlein** [comment]
Thank you for the report @jochem725!

The atomic schema is a bit difficult to change, but until we do that, I think the tracker should truncate the URL scheme to 16 characters in the workaround (the deep link entity will still have the full URL scheme). We'll discuss this in the team and open a PR.

**Comment by jochem725** [comment]
@matus-tomlein I see, for now I'll stick with the truncate solution then. Thank you :)

**Comment by matus-tomlein** [comment]
This has been fixed in the underlying iOS and Android trakers
