### ISSUE TITLE
iOS tracker does not respect emitRange parameter

### ISSUE THREAD

**Issue by jochem725** [snowplow-incubator/snowplow-react-native-tracker#194]
**Describe the bug**
Events arrive in our data warehouse in batches of up to 250 events with the same sent timestamp while the emitRange is set to 25.

**To Reproduce**
Create a tracker with the `logLevel: "verbose"` and the following emitterConfig
```typescript
{
    bufferOption: "large", // 25 events
    emitRange: 25,
    threadPoolSize: 15,
    byteLimitPost: 150000,
    byteLimitGet: 150000
}
```

- Disconnect the device / simulator from the internet
- Track a large number of events (~250 or more)
- Reconnect the device to the internet
- In the debug log; you'll find a log indicating that more events than the allowed emitRange were sent `Success Count: 250`

**Expected behavior**
We expect only 25 events with the same sent and collector timestamp to end up in our data warehouse. 

I believe this issue is caused by the `emittableEventsWithQueryLimit` method in the SQLiteEventStore ignoring the input parameter (the emitRange). It seems to be using a default value of 250 instead.

- Emitter fetching events using `emitRange`
https://github.com/snowplow/snowplow-ios-tracker/blob/ec912a566073615ebcc9dc3a4c6b96a1cc6ed7e7/Snowplow/Internal/Emitter/SPEmitter.m#L317
- SQLiteEventStore `emittableEventsWithQueryLimit`
https://github.com/snowplow/snowplow-ios-tracker/blob/ec912a566073615ebcc9dc3a4c6b96a1cc6ed7e7/Snowplow/Internal/Storage/SPSQLiteEventStore.m#L178

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.4
 - Version snowplow-react-native-tracker 1.4.0

**Additional context**
Partially related to this; for lower values of the bufferOption (e.g. `single`) we still see events arriving in batches of 250 with the same sent timestamp, but each event will be sent in a single request. This causes issues with the derived timestamp field because it relies on the assumption that network time is close to 0, but since only a limited number of events is sent in parallel you can end up with a very large difference between the sent timestamp and the collector timestamp causing very big inaccuracies in the derived timestamp. I'm wondering if there is a reason why the sent timestamp isn't set when the event is actually being sent (for example [here](https://github.com/snowplow/snowplow-ios-tracker/blob/release/4.2.0/Snowplow/Internal/NetworkConnection/SPDefaultNetworkConnection.m#L176))

**Comment by matus-tomlein** [comment]
Thank you for reporting the problem and identifying the problematic code path, @jochem725! That is indeed a bug, we will address it in the next releases.

**Comment by matus-tomlein** [comment]
This has been fixed in the underlying iOS tracker.
