### ISSUE TITLE
Update native trackers to version 5

### ISSUE THREAD

**Issue by jaspermeijaard** [snowplow-incubator/snowplow-react-native-tracker#199]
Currently both native trackers are checked out on version 4. Are there any plans to update to version 5?

**Comment by matus-tomlein** [comment]
Yes, thank you for raising the issue @jaspermeijaard! We plan to update the native trackers to 5 in an upcoming release.

**Comment by jaspermeijaard** [comment]
@matus-tomlein Awesome! Much appreciated! Do you have any idea on the timeline of that? This quarter, next quarter or maybe later?

**Comment by matus-tomlein** [comment]
Unfortunately I can't give a hard deadline, but we will aim for updating it this quarter.
