### ISSUE TITLE
[Fabric] - Snowplow crashes with new architecture enabled

### ISSUE THREAD

**Issue by p-sebastian** [snowplow-incubator/snowplow-react-native-tracker#212]
**Describe the bug**
Immediate crash when `createTracker` is called with new architecture enabled

**To Reproduce**
```typescript
import { createTracker, ReactNativeTracker } from '@snowplow/react-native-tracker'

export const App: React.FC = () => {
 createTracker(...)
 return null
}
```

**Expected behavior**
- Should not crash with Fabric enabled

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: 17.5.1
 - Version `"@snowplow/react-native-tracker": "^2.1.1"`

**Comment by miike** [comment]
@p-sebastian Could you please attach the crash report or logs please?

**Comment by p-sebastian** [comment]
@miike rename to ips

[PenguBeta-2024-07-29-112958.txt](https://github.com/user-attachments/files/16411402/PenguBeta-2024-07-29-112958.txt)


<img width="1279" alt="Screenshot 2024-07-29 at 12 42 41" src="https://github.com/user-attachments/assets/1d405bf0-ffb7-438d-abaa-90956e676a57">

**Comment by jannisringwald** [comment]
@miike @matus-tomlein is there any timeline on this?

**Comment by miike** [comment]
@jannisringwald I'm going to close this out in favour of the support ticket #41825. There has been a ticket to track this internally but no timeline as the New Architecture is still experimental with no official release yet.

**Comment by dkjepben** [comment]
We are getting this error and are now the only blocker for us to upgrade to newest React Native 0.75.
Is there any news on getting a fix to this? 

The new architecture starts to be the default configuration for a RN project.

**Comment by jannisringwald** [comment]
Hey guys,

with the React Native 0.76 release yesterday the new Architecture got enabled by default. 

The Snowplow Tracker is the only Library in our Stack which is crashing with the new Architecture. 


Is there now any timeline?  @miike @matus-tomlein 

https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture

**Comment by dkjepben** [comment]
Same as @jannisringwald

**Comment by matus-tomlein** [comment]
Thanks for checking back about this @dkjepben and @jannisringwald! We are looking into supporting the new architecture in the tracker, can't be very specific about the timeline, but the plan is to add the support in Q4 this year.

**Comment by d-moreira** [comment]
hey @matus-tomlein, how's support for the new arch going? Any timelines that you can share?

**Comment by matus-tomlein** [comment]
Hi @d-moreira, we added support for the new architecture in [version 2.1.2](https://github.com/snowplow/snowplow-react-native-tracker/releases/tag/2.1.2). This version uses the interoperability layer, but fully supports the new architecture apps.

Moreover, we are working on the next major version of the RN tracker that will be JavaScript-only (without any native modules) and will not require the interoperability layer and add support for Expo Go and React Native for Web. We are planning to release this early next year.
