### ISSUE TITLE
Update ios Tracker dependency to remove mandatory dynamic build

### ISSUE THREAD

**Issue by flaviomax** [snowplow-incubator/snowplow-react-native-tracker#22]
I am facing issues when trying to integrate this tracker to my existing app. I use multiple other libraries, as shown in my Podfile:

```
project 'myapp.xcodeproj'

platform :ios, '9.0'

target 'myapp' do
  pod 'React', :path => './../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTAnimation',
    'RCTVibration',
    'RCTSettings',
    'RCTWebSocket',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTNetwork',
    'RCTLinkingIOS',
    'RCTImage',
    'ART',
    'RCTPushNotification',
  ]
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'
  pod 'Firebase/RemoteConfig', '~> 6.2.0'
  pod 'Firebase/Database', '~> 6.2.0'
  
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'CodePush', :path => './../node_modules/react-native-code-push/CodePush.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'
  pod 'react-native-config', :path => '../node_modules/react-native-config/react-native-config.podspec'
  pod 'react-native-fbsdk', :path => './../node_modules/react-native-fbsdk/react-native-fbsdk.podspec'
  pod 'react-native-intercom', :path => '../node_modules/react-native-intercom/react-native-intercom.podspec'
  pod 'react-native-mixpanel', :path => './../node_modules/react-native-mixpanel/react-native-mixpanel.podspec'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview/react-native-webview.podspec'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions/ReactNativePermissions.podspec'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch/RNBackgroundFetch.podspec'
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation/RNBackgroundGeolocation.podspec'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info/RNDeviceInfo.podspec'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n/RNI18n.podspec'
  pod 'RNVectorIcons', :path => './../node_modules/react-native-vector-icons/RNVectorIcons.podspec'
  pod 'yoga', :path => './../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

end
```

The issue is that this tracker mandates the use of `use_frameworks` within the Podfile, and that conflicts with other libraries that do not support it (specifically, in this case, `AppCenter`), and so `pod install` fails.

I tried adding the pod manually to the file, by adding:

```
pod 'FMDB', :modular_headers => true
pod 'RNSnowplowTracker', :path => '../node_modules/@snowplow/react-native-tracker/ios/RNSnowplowTracker.podspec', :modular_headers => true
``` 

This makes `pod install` run successfully, but the Build phase in XCode fails for RNSnowplowTracker.

I am currently trying to clone this repo and build the pod static version on my own, but that is not replicable. It would be nice to have a way to import a static version of this library.

**Comment by jordanAtSlice** [comment]
@colmsnowplow Just wanted to let you know that this issue specifically is blocking us from getting the native tracker integrated. Curious if there is any progress on this?

**Comment by colmsnowplow** [comment]
Thanks for reporting @flaviomax and thanks for the nudge @jordanAtSlice .

It's not likely that we'll resolve it this month, there's a chance we'll be able to take a look in December, but the likelier outcome is early next year as it stands with the roadmap.

I think it's possible to manually install as @flaviomax suggests and then manually link the library into your project - this is likely painful but it's got a good chance of working.

Sorry not to be able to give you a better answer than that - this project is in alpha phase and is very much a work in progress right now, so there's still a lot of unknowns and we expect to run into roadblocks here and there.

**Comment by wcaf07** [comment]
@BrittanySerrador Have you faced this issue as well? Is there any confirmed workaround that works?

**Comment by BrittanySerrador** [comment]
@wcaf07 I'm on the same team as @jordanAtSlice so yes, currently struggling through. We're considering trying to manually link it but it's not something I've done before so if I get it working, I'll get back to you for sure!

**Comment by colmsnowplow** [comment]
Hi @wcaf07 , @BrittanySerrador , @jordanAtSlice - I've released a milestone release which I believe fixes the issue.

It's not marked as latest (some work is to be done before it's ready for integration into the project) - so you'll need to specify the exact version: `npm install @snowplow/react-native-tracker@0.1.0-alpha.15-M1`.

Let me know how you get on.

**Comment by colmsnowplow** [comment]
Oh, I forgot to tag the initial reporter! @flaviomax see last comment. :)

**Comment by wcaf07** [comment]
Thanks for the news @colmsnowplow :) I am putting my hands on the integration today. I'll let you guys know anything.

**Comment by wcaf07** [comment]
Hello guys, just sharing my experience here, after adding the specific version (as mentioned above) and the dependency on Podfile, I got the following error after runnig `pod install`:

> CocoaPods could not find compatible versions for pod "SnowplowTracker":
  In Podfile:
    RNSnowplowTracker (from `../node_modules/@snowplow/react-native-tracker/ios/RNSnowplowTracker.podspec`) was resolved to 1.0.0, which depends on
      SnowplowTracker (= 1.2.0-M1)
None of your spec sources contain a spec satisfying the dependency: `SnowplowTracker (= 1.2.0-M1)`.

So I set on my Podfile.lock the RNSnowplowTracker to version 1.0.0, and run the `pod update` command to get it working. We have tested and it is working fine. Thank you very much for the update @colmsnowplow  :)

**Comment by flaviomax** [comment]
Hi all!
I actually work on the same team as @wcaf07, so I can confirm this works!

Thanks a lot, guys

**Comment by colmsnowplow** [comment]
Thanks for reporting back! 

Re-opening the issue for my own reference as it'll need to be integrated into a full release (pending iOS tracker release first).

**Comment by colmsnowplow** [comment]
Hey @flaviomax / @wcaf07 (or anyone else on the thread) - could one of you give me an example of a library that reproduces this problem? Would be useful once we get to automated testing. :)

**Comment by flaviomax** [comment]
Hi @colmsnowplow , the issue for us was specifically with the AppCenter lib. It does not support the use_frameoworks! flag, as described here:
https://github.com/microsoft/appcenter-sdk-react-native/issues/714
