### ISSUE TITLE
'SnowplowTracker/SPTracker.h' file not found

### ISSUE THREAD

**Issue by wcaf07** [snowplow-incubator/snowplow-react-native-tracker#27]
After setup of Demo App as the guide shows. I am finding the following error on xcode:

`'SnowplowTracker/SPTracker.h' file not found`

Any clues on how to solve this issue?

**Comment by wcaf07** [comment]
@colmsnowplow any comments about it? Have you guys faced this issue?

**Comment by BrittanySerrador** [comment]
@wcaf07 have you gone into xcode and tried Product > Clean? I would also go into the utilities pane on the right side for that file and check that it's connected to the correct target.
<img width="260" alt="Screen Shot 2019-11-26 at 8 56 34 AM" src="https://user-images.githubusercontent.com/47982084/69639562-ba63e080-102a-11ea-80bc-734b561475bb.png">
<img width="243" alt="Screen Shot 2019-11-26 at 8 56 20 AM" src="https://user-images.githubusercontent.com/47982084/69639563-bb950d80-102a-11ea-9904-4f0f71fb84da.png">

**Comment by wcaf07** [comment]
@BrittanySerrador Tks just worked for me! :)

**Comment by BrittanySerrador** [comment]
@wcaf07 Perfect! 😄
