### ISSUE TITLE
Fix Android Numeric type bug

### ISSUE THREAD

**Issue by gziolle** [snowplow-incubator/snowplow-react-native-tracker#4]
In `android/src/main/java/com/snowplowanalytics/react/tracker/RNSnowplowTrackerModule.java`
`trackStructuredNumber` expects a Number parameter, which is an abstract class
```
@ReactMethod
    public void trackStructuredEvent(String category, String action, String label,
                                     String property, Number value, ReadableArray contexts) {
        Structured trackerEvent = EventUtil.getStructuredEvent(category, action, label,
                property, value, contexts);
        if (trackerEvent != null) {
            tracker.track(trackerEvent);
        }
    }
```
When I try to run the DemoApp and send an event, it crashes:
![Screenshot_1569520435](https://user-images.githubusercontent.com/1500586/65712959-82faa700-e06e-11e9-889c-a3d7ed8ea815.png)

If I change it to `Double`, it works.

**Comment by colmsnowplow** [comment]
Fixed in alpha.12
