### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by gziolle** [snowplow-incubator/snowplow-react-native-tracker#5]
Config:
    "@snowplow/react-native-tracker": "^0.1.0-alpha.10",
    "react": "16.8.3",
    "react-native": "0.59.9"
    IOS 13 (XCode 11)

Steps(Commands):
 - react-native init sample --version react-native@0.59.9
 - yarn add @snowplow/react-native-tracker
 - react-native link @snowplow/react-native-tracker (not sure if is necessary)
 - react-native run-ios --simulator="iPhone 8"

When I try to run, this error happens:
```
❌  /Users/guilhermeziolle/git/test/pier-test/sample/node_modules/@snowplow/react-native-tracker/ios/RNSnowplowTracker.m:2:9: 'SnowplowTracker/SPTracker.h' file not found

#import <SnowplowTracker/SPTracker.h>
  ^       ~
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening sample.xcodeproj
```
Is there any other step to follow in order to set this lib to iOS?

**Comment by colmsnowplow** [comment]
Hi @gziolle,

Thanks for logging - I'm yet to clean up the branch and merge to master (with update to readme) but this and the other bugs you've logged are fixed in alpha.12.

Steps to run ios:

For iOS, the tracker's dependencies must be installed as frameworks.

First add use_frameworks! to your app's Podfile. Then:

`cd ios && pod install && cd ..`

Run the app with: `react-native run-ios` from the root of the project.

Let me know if you have any issues.

**Comment by colmsnowplow** [comment]
Using this issue as marker for upcoming alpha release's readme update.

**Comment by gziolle** [comment]
Hello @colmsnowplow! Thank you very much for your reply!
I saw your pull request. I don't know how you guys work with open-source projects, but if it needs to be reviewed, I can do it.

Thanks again!

**Comment by colmsnowplow** [comment]
Thanks @gziolle - can't harm to get an external review - I'm tinkering with a couple of additions in another branch (which I may also include in this PR). Once it's ready I'll add you as a reviewer along with one of my colleagues. Thanks for offering!

**Comment by colmsnowplow** [comment]
@gziolle I can't add you as a reviewer as you're external to the org, but if you could add any comments here that would be great! https://github.com/snowplow-incubator/snowplow-react-native-tracker/pull/15
