### ISSUE TITLE
Get Session Context Data

### ISSUE THREAD

**Issue by max-tgam** [snowplow-incubator/snowplow-react-native-tracker#53]
We are using Snowplows user_id/domain/session_id as a fallback ID (in conjunction with couple of other IDs) in some of our personalization APIs.

On web and in Native apps it is fairly easy to get, however in React Native additional considerations should be taken. The value cannot be just returned back but SDK needs to use either promises or callbacks inside SDK.

For Android the call would include following sample modification to the code:
```
@ReactMethod
    public void getSessionUserId(final Promise promise) {
        try {
            Map<String, Object> sessionData = tracker.instance().getSession().getSessionValues();
            Object result = sessionData.get(Parameters.SESSION_USER_ID);
            promise.resolve(result);
        } catch (Exception e) {
            promise.reject("Cannot obtain SESSION_USER_ID");
        }
    }
```

For iOS it would be something like:
```
RCT_EXPORT_METHOD(getSessionUserId:(RCTPromiseResolveBlock)resolve 
                  rejecter:(RCTPromiseRejectBlock)reject
                 ) {
  NSError *error;
  NSString *contents = [self.tracker getSessionUserId];
  if (contents) {
    resolve(contents);
  } else {
    reject(@"data_issue", @"Cannot obtain SESSION_USER_ID", error);
  }
}
```

Then inside the `App.js` we would need to do something like:
```
const myFunction = (async () => {
      const SUID = await Tracker.getSessionUserId();
      // Call API if promise is resolved
      //console.log(SUID);
    })();
```

What would be the best course of action to integrate such code? Should there be a plug-in functionality that allows extending Snowplow React Native SDK with customer specific code or can this code be added to SDK?

**Comment by max-tgam** [comment]
@colmsnowplow We are using above code in our fork of Snowplow React Native SDK but it would be nice to have a more organic way to integrate it into main repo instead.

**Comment by colmsnowplow** [comment]
Hi @max-tgam,

Thanks for raising & including detail. 

So thus far we haven't put much thought into more advanced methods like callbacks - we've been focused on what the minimal featureset is for a v1. This strikes me as something we'll probably look at post-v1 - I've raised it internally & we'll figure out where it fits the priority list.

**Comment by max-tgam** [comment]
@colmsnowplow Ok sound fair. Thanks!
