### ISSUE TITLE
Add explicit argument validation

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow-incubator/snowplow-react-native-tracker#59]
Once methods have been refactored (#58), we should add explicit argument validation.

This has the added advantage of allowing us to throw where something is instrumented incorrectly, which should improve developer experience (since currently it's possible for the tracker to silently fail if instrumented incorrectly)

**Comment by adatzer** [comment]
This is resolved as part of #128 .
More specifically, tracker methods do validate their arguments explicitly and "throw" specific [logMessages](https://github.com/snowplow-incubator/snowplow-react-native-tracker/blob/809d74f50607f751283ee5b60c4f9b8d501ee5ca/src/constants.ts#L16).
Concerning the track methods, explicit argument validation concerns the required properties of the event and the optional custom contexts. This was also discussed in the #128 PR review and maybe the extend of validation is something to be reconsidered in the future.
Closing.
