### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow-incubator/snowplow-react-native-tracker#62]

**Comment by jdmunro** [comment]
Hey @colmsnowplow - do you know when this is likely to happen? We are integrating [Fossa](https://fossa.com) into our workflow soon as we are looking to bolster the license compliancy of our apps.

**Comment by colmsnowplow** [comment]
@jdmunro definitely in the next release. Timeline for that is optimistically within the next 2 weeks, pessimistically but confidently within 4 weeks. 

I hope that gives you a good enough metre stick to go by? Apologies that it's hard to be more specific - workflows have been somewhat disrupted recently by sick leave within the team.

**Comment by jdmunro** [comment]
@colmsnowplow Thanks for the update! That's cool - just wanted to get it on our radar so that we can plan accordingly. Thanks! 🎉
