### ISSUE TITLE
Feature request: Tracker.initialize should return a promise

### ISSUE THREAD

**Issue by jdmunro** [snowplow-incubator/snowplow-react-native-tracker#66]
Because of the way the RN bridge currently works, there is a potentially problematic race condition with initialising the tracker and logging your first event/using the tracker.

Consider the following simplified example:

```js
Tracker.initialize(...)
Tracker.setSubjectData(...) // Potential crash here
```

Because the RN bridge is asynchronous, there is no guarantee that the tracker has actually initialised by the time the 2nd line is called. At least on Android, this can result in a potential exception being thrown due to the native tracker not being initialised: https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Tracker.java#L91

The way other SDKs have solved this is to return a promise from the `initialize` method, so that we can await the native execution. This could look something like this:

```js
const initPromise = Tracker.initialize(...)
// ... 
await initPromise // A resolved promise will always resolve immediately on subsequent await/then
Tracker.setSubjectData(...) 
```

Alternatively:

```js
const initPromise = Tracker.initialize(...)
// ... 
initPromise.then(() => Tracker.trackStructuredEvent(...)
```

Some other considerations:

1. This could be part of the public API, or you could abstract it and handle it internally in the JS layer of the bindings
2. `Tracker.initialize` could also return an instance of an object, so that we can reference that later on, rather than an ostensibly stateless API

Here's how it's solved in `react-native-mixpanel`: https://github.com/davodesign84/react-native-mixpanel/blob/master/index.js#L38

**Comment by colmsnowplow** [comment]
Thanks for reporting - feels like a solvable problem, will look to get this into the next release.
