### ISSUE TITLE
Pass application context to the subject on Android

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow-incubator/snowplow-react-native-tracker#79]
On Android, [the application context should be passed to the subject](https://github.com/snowplow/snowplow-android-tracker/blob/9726d22ead6347cc4a493f65fb87f2a1c9d47363/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Subject.java#L73) in order to pick up certain values.

[This isn't configured on Android in react-native](https://github.com/snowplow-incubator/snowplow-react-native-tracker/blob/2a0ea144d61f87219c638efc317ec2de5264dbc5/android/src/main/java/com/snowplowanalytics/react/tracker/RNSnowplowTrackerModule.java#L68).

Passing react context may work, or it may need to be [grabbed manually](https://github.com/facebook/react-native/issues/3895).

Users experiencing this issue before fix is released can use the `setSubjectData()` method to configure any data they require.

**Comment by adatzer** [comment]
This is resolved as part of #128 .
More specifically, by upgrading the Android tracker to v2, the android context is being passed as an argument to the `createTracker` native method. [Relevant code](https://github.com/snowplow-incubator/snowplow-react-native-tracker/blob/809d74f50607f751283ee5b60c4f9b8d501ee5ca/android/src/main/java/com/snowplowanalytics/react/tracker/RNSnowplowTrackerModule.java#L121).
Closing.
