### ISSUE TITLE
Allow for a 'page ping'-like event for screen views (screen-ping?)

### ISSUE THREAD

**Issue by andy-clapson** [snowplow-incubator/snowplow-react-native-tracker#90]
I would like to be able to reliably calculate how long a user stays active on a screen in a mobile app - it can be difficult to handle events like a minimized app or screen off events.

An event analogous to the page_ping in the web data model would be useful - a `screen_ping` event, with a user-configurable interval?

For now, I am using the time between observed screen views, with some edge-case-handling involving app minimization events, in tandem with parsing intervals between screen views tha feel "too long" - but of course this is somewhat arbitrary.

**Comment by colmsnowplow** [comment]
Thanks @andy-clapson.

I agree that this would be a nice addition. We have some tooling in the native trackers (which haven't been added to this one yet) which might help - timing events. However they don't do anything around ensuring the user is still engaged like page pings do.

Your timing is quite good though - just this week this exact topic was raised in relation to the native trackers, and we're looking into what the solution might look like. It's still early days but I'm optimistic that we will implement something better on it - and when we do so we'll get it added to RN too.

We'll also take a look at whether adding timing events is useful next time we're scoping an RN release. 

Thanks for raising!

**Comment by zhconsultancyservices** [comment]
@colmsnowplow , was this feature released?

**Comment by shalinibnair** [comment]
@colmsnowplow , Was this feature released? I was looking for this in the documentation but could not find any.
Also if this is not available, please suggest a workaround

**Comment by AlexBenny** [comment]
Hi @shalinibnair ,
As said, there is an ongoing debate around screen-ping on mobile. At the moment, we don't plan to work on this feature. The main reason is that the mobile trackers are already able to track lifecycle events (`application_foreground` and `application_background` events) and, in pair with the ScreenView events, they can be used to calculate the engagement of the user in a screen without needing the page-ping event.

I would suggest to continue the conversation about a possible workaround in Discourse. The forum that we use as a knowledge base for the community. Actually, you can find a [similar discussion](https://discourse.snowplowanalytics.com/t/tracking-dwell-time-or-page-pings-using-unity-swift-trackers/6368/2) in there about possible workarounds.
