### ISSUE TITLE
Library is throwing Null Pointer Exception on Android

### ISSUE THREAD

**Issue by Freire71** [snowplow-incubator/snowplow-react-native-tracker#96]
**Describe the bug**
Snowplow library is throwing  an error
**To Reproduce**
 - React-Native 0.61.5
 - Run **yarn android**
- When build is finished try to do any action 

**Expected behavior**
App should not crash
**Screenshots**
![image](https://user-images.githubusercontent.com/26610141/96805608-669f7a00-13e8-11eb-8d7e-811e5bd22588.png)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 5
 - OS: Android
 - Version: Android 9

**Comment by colmsnowplow** [comment]
I haven't been able to reproduce this. The below works just fine for me, no errors, no app crashes on interactions:

`cd DemoApp/`
`yarn install`
`yarn android`

I also tested on RN 0.61.5. 

So it appears to me not to be a bug and is likely down to something external, but if you can provide steps to reproduce we'll be happy to look into it further.

**Comment by colmsnowplow** [comment]
Closing as it seems not to be a bug
