### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by rahulsmehta** [snowplow-incubator/snowplow-react-native-tracker#97]
**Is your feature request related to a problem? Please describe.**
We currently use TypeScript for our React Native projects and are in the process of integrating a project with our event tracking. We've been able to get Amplitude configured but also maintain an internal mirror of events using Snowplow. We'd like to use this library to wire up our app to our internal event log.

**Describe the solution you'd like**
Adding type definition files (`.d.ts` files) to the repo to declare the signatures for the core tracker methods according to [this section of the TypeScript documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Describe alternatives you've considered**
An alternative would be to add our own typings for snowplow in our repo, but this seems to be additive to the project in general. Another option is to create a separate typings package (ie. `@types/snowplow-react-native-tracker`) that users would install alongside this one if they wanted to use it in TypeScript.

**Additional context**
I'd be happy to contribute the `.d.ts` files if this is a PR the maintainers would accept.

**Comment by colmsnowplow** [comment]
Hi @rahulsmehta,

Thanks for raising. This would be a welcome contribution for sure!

**Comment by rahulsmehta** [comment]
That's great @colmsnowplow -- unfortunately we just checked and the library in its current state won't work with our app setup (Expo managed workflow) so we're going with a workaround using the nodejs snowplow tracker. Once we eject/are building the iOS/Android bundles separately, we'll revisit & definitely make this contribution.

**Comment by colmsnowplow** [comment]
That's a shame. I think Expo doesn't like native modules, so not a huge amount we can do with this project to make it compatible :( 

Do let us know about your experiences/feedback using the Node.js tracker though! We are keen to give that one some love next year.

**Comment by rahulsmehta** [comment]
Will do @colmsnowplow -- we actually just got a pure JS/TypeScript implementation working for RN on top of the nodejs tracker that shims in some of the device platform properties etc. We're planning on open-sourcing the package in a couple weeks

**Comment by Hannes-Endare** [comment]
```
declare module '@snowplow/react-native-tracker' {
  export interface TrackerProps {
    // required
    endpoint: string,
    namespace: string,
    appId: string,
    // optional
    method?: string,
    protocol?: string,
    platformContext?: boolean,
    base64Encoded?: boolean,
    applicationContext?: boolean,
    lifecycleEvents?: boolean,
    screenContext?: boolean,
    sessionContext?: boolean,
    foregroundTimeout?: number,
    backgroundTimeout?: number,
    checkInterval?: number,
    installTracking?: boolean,
  }

  export interface SubjectData {
    // optional
    userId?: string,
    screenWidth?: number, 
    screenHeight?: number,
    colorDepth?: number,
    timezone?: string, 
    language?: string,
    ipAddress?: string,
    useragent?: string,
    networkUserId?: string,
    domainUserId?: string,
    viewportWidth?: number,
    viewportHeight?: number,
  }

  export interface SelfDescribingEvent {
    // required
    'schema': string,
    'data': Object,
  }

  export interface StructuredEvent {
    // required
    category: string,
    action: string,
    // optional
    label?: string,
    property?: string,
    value?: number,
  }

  export interface ScreenViewEvent{
    // required
    screenName: string,
    // optional
    screenType?: string,
    transitionType?: string,
  }

  export interface PageViewEvent {
    // required
    pageUrl: string, 
    // optional
    pageTitle?: string,
    pageReferrer?: string,
  }

  export default class Tracker {
    static initialize(props: TrackerProps): Promise<boolean>;
    static setSubjectData(props: SubjectData): void;
    static trackSelfDescribingEvent(event: SelfDescribingEvent, contexts?: Array<SelfDescribingEvent>): void;
    static trackStructuredEvent(event: StructuredEvent, contexts?: Array<SelfDescribingEvent>): void;
    static trackScreenViewEvent(event: ScreenViewEvent, contexts?: Array<SelfDescribingEvent>): void;
    static trackPageViewEvent(event: PageViewEvent, contexts?: Array<SelfDescribingEvent>): void;
  }
}
```
This is the .d.ts file I created

**Comment by zhconsultancyservices** [comment]
We are facing a block because the tracker cannot be integrated with Expo. Is there any workaround available?

**Comment by matus-tomlein** [comment]
Hey @zhconsultancyservices, unfortunately, we do not have a workaround for Expo ready. Likely the only approach to get a tracker running there would be to adopt the NodeJS tracker (see [docs here](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/node-js-tracker/)) as suggested above. We plan to look into this and hope to come back with an answer for you.
