### ISSUE TITLE
Upgrade obj-c tracker to 1.6.2

### ISSUE THREAD

**Issue by willcaul** [snowplow-incubator/snowplow-react-native-tracker#98]
**Describe the bug**
The obj-c tracker should be upgraded to version `1.6.2` to pull in the fix for the memory leak on iOS: https://github.com/snowplow/snowplow-objc-tracker/pull/562

**To Reproduce**
See https://github.com/snowplow/snowplow-objc-tracker/issues/559

**Expected behavior**
The memory leak should not occur.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: any iOS device
 - OS: iOS
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by colmsnowplow** [comment]
Thanks for raising - I'm working with the team to figure out scheduling the fix

**Comment by colmsnowplow** [comment]
Should be resolved now on latest - let us know if you run into any issues. :)

**Comment by willcaul** [comment]
> Should be resolved now on latest - let us know if you run into any issues. :)

Ok will do. Thanks @colmsnowplow!

**Comment by colmsnowplow** [comment]
Hth, thanks for raising.
